<a href="https://colab.research.google.com/github/vaniago/base-numpy/blob/main/IntroNumpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Broadcasting

*Broadcasting* é um método de aplicação de operações aritméticas entre matrizes de dimensões diferentes.

##Broadcasting de escalar

O caso mais simples, que já vimos, é a atribuição de um valor escalar a uma matriz qualquer.

In [ ]:
import numpy as np

lista=[[12,20,34],[13,21,35],[14,22,36]]
matriz=np.asarray(lista)
print('matriz original:')
print(matriz)
print("Broadcasting do valor 5")
matriz[:]=5
print('matriz[:]=5 \n',matriz)

matriz original:
[[12 20 34]
 [13 21 35]
 [14 22 36]]
Broadcasting do valor 5
matriz[:]=5 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


As operações aritméticas com escalares também resultam por *broadcasting*

In [ ]:
import numpy as np

lista=[[12,20,34],[13,21,35],[14,22,36]]
matriz=np.asarray(lista)
print('matriz original:')
print(matriz)
print("Broadcasting da divisão inteira por 5")
matriz=matriz//5
print('matriz=matriz//5 \n',matriz)

matriz original:
[[12 20 34]
 [13 21 35]
 [14 22 36]]
Broadcasting da divisão inteira por 5
matriz=matriz//5 
 [[2 4 6]
 [2 4 7]
 [2 4 7]]


Desse modo, podemos realizar operações aritméticas sobre elementos de matrizes.
Neste exemplo, vamos substituir os valores originais das matrizes pelo seu escore normalizado z, a partir da média e do desvio-padrão:

In [ ]:
import numpy as np
#gera a matriz normalizada a partir do 
#escore z=(x-média)/(desvpadrão)

lista=[[12,20,34],[13,21,35],[14,22,36]]
matriz=np.asarray(lista)
media=matriz.mean()
desvpad=matriz.std()
print('matriz original=')
print(matriz)
print("matriz normalizada")
normalizada=(matriz-media)/desvpad
print('normalizada= \n',normalizada)

matriz original=
[[12 20 34]
 [13 21 35]
 [14 22 36]]
matriz normalizada
normalizada= 
 [[-1.20498963 -0.32863353  1.20498963]
 [-1.09544512 -0.21908902  1.31453414]
 [-0.9859006  -0.10954451  1.42407865]]


##*Broadcasting* entre matrizes de dimensões diferentes

O *broadcasting* entre matrizes de dimensões diferentes segue algumas regras.

##Regra da compatibilidade de dimensões
As matrizes precisam ter:    
* ou um valor igual para a mesma dimensão;
* ou o valor 1 para dimensões diferentes.


###Exemplo



In [ ]:
import numpy as np

l1=[[12,20,34],[13,21,35],[14,22,36]]
l2=[[1,2,3]]

m1=np.asarray(l1) #m1 é 3x3
m2=np.asarray(l2) #m2 é 1x3
print('m1=\n',m1)
print('m2=\n',m2)
print('m1-m2=\n',m1-m2)

m1=
 [[12 20 34]
 [13 21 35]
 [14 22 36]]
m2=
 [[1 2 3]]
m1-m2=
 [[11 18 31]
 [12 19 32]
 [13 20 33]]


Se aumentarmos uma dimensão em m2, tornado-o um vetor de 1x4, teremos erro *ValueError*:

In [ ]:
import numpy as np

l1=[[12,20,34],[13,21,35],[14,22,36]]
l2=[[1,1,1,1]]
m1=np.asarray(l1) #m1 é 3x3
m2=np.asarray(l2) #m2 agora é 1x4
print('m1=\n',m1)
print('m2=\n',m2)
print('m1-m2=\n',m1-m2)

m1=
 [[12 20 34]
 [13 21 35]
 [14 22 36]]
m2=
 [[1 1 1 1]]


ValueError: ignored

Se mudarmos m2 para a dimensão (3x1), volta a funcionar e, dependendo dos valores, o resultado será diferente:      

In [ ]:
import numpy as np

l1=[[12,20,34],[13,21,35],[14,22,36]]
l2=[[1],[2],[3]]
m1=np.asarray(l1) #m1 é 3x3
m2=np.asarray(l2) #m2 é 3x1
print('m1=\n',m1)
print('m2=\n',m2)
print('m1-m2=\n',m1-m2)
print(m1.shape)
print(m2.shape)

m1=
 [[12 20 34]
 [13 21 35]
 [14 22 36]]
m2=
 [[1]
 [2]
 [3]]
m1-m2=
 [[11 19 33]
 [11 19 33]
 [11 19 33]]
(3, 3)
(3, 1)


###Com mais dimensões

Suponha uma matriz m1 com dimensões 3x4x5.
Pela regra de compatibilidade, serão compatíveis:    
* m2 4x5
* m3 1x4x5
* m4 3x4x1
* m5 3x1x5

Vamos aos exemplos:

In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5)
print('m1=\n',m1)
m2=np.arange(20).reshape(4,5)
print('m2=\n',m2)
print('m1-m2=\n',m1-m2)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m2=
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
m1-m2=
 [[[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[20 20 20 20 20]
  [20 20 20 20 20]
  [20 20 20 20 20]
  [20 20 20 20 20]]

 [[40 40 40 40 40]
  [40 40 40 40 40]
  [40 40 40 40 40]
  [40 40 40 40 40]]]


###m1 3x4x5 e m3 1x4x5:    


In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5)
print('m1=\n',m1)
m3=np.arange(20).reshape(1,4,5)
print('m3=\n',m3)
print('m1-m3=\n',m1-m3)
print('m2==m3\n',m2==m3)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m3=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]
m1-m3=
 [[[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[20 20 20 20 20]
  [20 20 20 20 20]
  [20 20 20 20 20]
  [20 20 20 20 20]]

 [[40 40 40 40 40]
  [40 40 40 40 40]
  [40 40 40 40 40]
  [40 40 40 40 40]]]


NameError: ignored

###m1 3x4x5 e m4 3x4x1:    


In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5) #3*4*5=60
print('m1=\n',m1)
m4=np.arange(12).reshape(3,4,1) #3*4*1=12
print('m4=\n',m4)
print('m1-m4=\n',m1-m4)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m4=
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
m1-m4=
 [[[ 0  1  2  3  4]
  [ 4  5  6  7  8]
  [ 8  9 10 11 12]
  [12 13 14 15 16]]

 [[16 17 18 19 20]
  [20 21 22 23 24]
  [24 25 26 27 28]
  [28 29 30 31 32]]

 [[32 33 34 35 36]
  [36 37 38 39 40]
  [40 41 42 43 44]
  [44 45 46 47 48]]]


###m1 3x4x5 e m5 3x1x5:    


In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5) #3*4*5=60
print('m1=\n',m1)
m5=np.arange(15).reshape(3,1,5) #3*1*5=15
print('m5=\n',m5)
print('m1-m5=\n',m1-m5)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m5=
 [[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]
m1-m5=
 [[[ 0  0  0  0  0]
  [ 5  5  5  5  5]
  [10 10 10 10 10]
  [15 15 15 15 15]]

 [[15 15 15 15 15]
  [20 20 20 20 20]
  [25 25 25 25 25]
  [30 30 30 30 30]]

 [[30 30 30 30 30]
  [35 35 35 35 35]
  [40 40 40 40 40]
  [45 45 45 45 45]]]


##Compatibilidade no *broadcasting* de atribuições

A mesma regra de compatibilidade se aplica se queremos mudar o valor de uma matriz original a partir dos valores de uma matriz compatível.

Retomemos nosso exemplo, para m1 em dimensãoes 3x4x5 e compatíveis:    
     
* m2 4x5
* m3 1x4x5
* m4 3x4x1
* m5 3x1x5

###m1 3x4x5 e m2 4x5:    


In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5)
print('m1=\n',m1)
m2=np.arange(100,120).reshape(4,5) #20 valores pois 4*5=20
print('m2=\n',m2)
m1[:]=m2
print('m1[:]=m2\n',m1)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m2=
 [[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]
m1[:]=m2
 [[[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]]


###m1 3x4x5 e m3 1x4x5:    


In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5)
print('m1=\n',m1)
m3=np.arange(100,120).reshape(1,4,5)
print('m3=\n',m3)
m1[:]=m3
print('m1[:]=m3\n',m1)
print('m2==m3\n',m2==m3)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m3=
 [[[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]]
m1[:]=m3
 [[[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]]
m2==m3
 [[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


###m1 3x4x5 e m4 3x4x1:    


In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5)
print('m1=\n',m1)
m4=np.arange(100,112).reshape(3,4,1)
print('m4=\n',m4)
m1[:]=m4
print('m1[:]=m4\n',m1)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m4=
 [[[100]
  [101]
  [102]
  [103]]

 [[104]
  [105]
  [106]
  [107]]

 [[108]
  [109]
  [110]
  [111]]]
m1[:]=m4
 [[[100 100 100 100 100]
  [101 101 101 101 101]
  [102 102 102 102 102]
  [103 103 103 103 103]]

 [[104 104 104 104 104]
  [105 105 105 105 105]
  [106 106 106 106 106]
  [107 107 107 107 107]]

 [[108 108 108 108 108]
  [109 109 109 109 109]
  [110 110 110 110 110]
  [111 111 111 111 111]]]


###m1 3x4x5 e m5 3x1x5:    


In [ ]:
import numpy as np
m1=np.arange(60).reshape(3,4,5)
print('m1=\n',m1)
m5=np.arange(100,115).reshape(3,1,5)
m1[:]=m5
print('m5=\n',m5)
print('m1[:]=m5\n',m1)

m6=m5.reshape(5,3)
print("m6=\n",m6)

m7=m1.reshape(2,3,2,5)
print("m7=\n",m7)

m1=
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
m5=
 [[[100 101 102 103 104]]

 [[105 106 107 108 109]]

 [[110 111 112 113 114]]]
m1[:]=m5
 [[[100 101 102 103 104]
  [100 101 102 103 104]
  [100 101 102 103 104]
  [100 101 102 103 104]]

 [[105 106 107 108 109]
  [105 106 107 108 109]
  [105 106 107 108 109]
  [105 106 107 108 109]]

 [[110 111 112 113 114]
  [110 111 112 113 114]
  [110 111 112 113 114]
  [110 111 112 113 114]]]
m6=
 [[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]
 [112 113 114]]
m7=
 [[[[100 101 102 103 104]
   [100 101 102 103 104]]

  [[100 101 102 103 104]
   [100 101 102 103 104]]

  [[105 106 107 108 109]
   [105 106 107 108 109]]]


 [[[105 106 107 108 109]
   [105 106 107 108 109]]

  [[110 111 112 113 114]
   [110 111 112 113 114]]

  [[110 111 112 113 114]
 