<a href="https://colab.research.google.com/github/vaniago/base-numpy/blob/main/IntroNumpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vetorização

##A difícil vida dos loops em Python e a solução de Numpy

A tipagem dinâmica é uma das características mais interessantes de Python, mas ela possui um custo: os loops em Python se tornam lentos, porque a cada iteração o intepretador continua tendo que checar os tipos dos elementos da sequência.

Como vimos nas classes *numpy.ndarray* e *numpy.dtype*, as matrizes de Numpy são, efetivamente, tipadas e, portanto, as operações sobre os *ndarrays* podem ser mais velozes.

##Vetorização
Quando aprendemos a trabalhar com matrizes e iterações sobre matrizes, recaímos no clássico aninhamento de loops, para percorrer as linhas e colunas das matrizes.

A *vetorização* consiste numa forma de implementar uma linguagem de programação tal que seja possível realizar operações de matriz sobre matriz, sem precisar explicitar esses loops.

Considere o exemplo em que temos duas listas de números e queremos somar os seus valores.

Em Python simples, faríamos assim:

In [ ]:
lista1=[0,2,4,6,8]
lista2=[9,7,5,3,1]
soma=list()
for i in range(len(lista1)):
   soma.append(lista1[i]+lista2[i])
print(soma)    

[9, 9, 9, 9, 9]


Porém, Numpy nos dá uma abordagem mais rápida:

In [ ]:
import numpy as np
l1=[0,2,4,6,8]
l2=[9,7,5,3,1]
a1=np.asarray(l1)
a2=np.asarray(l2)
soma=a1+a2
print(soma)


[9 9 9 9 9]


*Vetorizar* é aplicar uma função diretamente sobre todos os valores de uma matriz ao mesmo tempo, em vez de aplicar a função elemento por elemento da matriz.

In [ ]:
import numpy as np
l1=[0,2,4,6,8]
l2=[9,7,5,3,1]
a1=np.asarray(l1)
a2=np.asarray(l2)

def por_elemento(lista1,lista2):
  soma=list()
  for i in range(len(lista1)):
     soma.append(lista1[i]+lista2[i])
  return soma

def vetorizado(a1,a2):
  soma=a1+a2
  return soma

%timeit -n 10000 -r 5 por_elemento(l1,l2)
%timeit -n 10000 -r 5 vetorizado(a1,a2)

10000 loops, best of 5: 1.23 µs per loop
10000 loops, best of 5: 623 ns per loop


#Nota: *timeit*

No interpretador IPyhton, que é usado no **colab*, tal como no *jupyter notebook*, temos os *magic commands*, que iniciam por '%'.

No caso, *timeit* mede o tempo de execução de um comando, com as opções:    
* -n<N>: executa o comando N vezes dentro de um loop de teste;

* -r<R>: número de repetições é R, default é 7.

* -t: o tempo é medido pela função *time.time*, default em Unix.

* -c: o tempo é medido pela função *time.clock*, default em Windows.

* -p<P>: os diígitos são apresentados com a precisão <P>, default é 3.

* -q: quiet. Não mostra resultados

* -o: retorna um TimeitResult que pode ser armazenado numa variável.

Mais sobre *magic commands* no intepretador IPython:    
[IPython documentation: Built-in magic commands](https://ipython.readthedocs.io/en/stable/interactive/magics.html)

#*ufuncs*: funções universais vetorizadas

Conforme o número de parâmetros podem ser:    
* unárias: aplicam-se sobre uma matriz;
* binárias: aplicam-se a mais de uma matriz.

##ufuncs unárias



| Função                                        | Descrição                                          |
|-----------------------------------------------|----------------------------------------------------|
| abs, fabs                                     | valor absoluto                                     |
| sqrt                                          | raiz quadrada                                      |
| square                                        | o quadrado                                         |
| exp                                           | exponencial                                        |
| log,log10,log2,log1p                          | logaritmo natural, base 10, base 2, base (1+x)     |
| sign                                          | sinal do elemento                                  |
| ceil                                          | 'teto', o menor inteiro maior ou igual ao valor    |
| floor                                         | 'piso', o maior inteiro menor ou igual ao valor    |
| rint                                          | arredonda para o próximo inteiro, preserva o dtype |
| isnan                                         | retorna array dizendo se e NaN                     |
| isfinite, isinf                               | retorna array dizendo se e finito, se e infinito   |
| sin, cos, tan, sinh, cosh, tanh               | funções trigonométricas                            |
| arcsin, arccos,arctan,arcsinh,arccosh,arctanh | funções trigonométricas inversas                   |
| logical_not                                   | retorna not(valor)                                 |

##Exemplos

In [ ]:
import numpy as np
l1=[0,2,4,6,8]
l2=[9,-7,5,-3,1]

a1=np.asarray(l1)
a2=np.asarray(l2)

print(a1)
print(a2)

print(np.square(a2))
print(np.sign(a2))
print(np.logical_not(a1))

[0 2 4 6 8]
[ 9 -7  5 -3  1]
[81 49 25  9  1]
[ 1 -1  1 -1  1]
[ True False False False False]


##ufuncs binárias

| Funçao                                                     | Descriçao                                                    |
|------------------------------------------------------------|--------------------------------------------------------------|
| add                                                        | adição                                                       |
| subtract                                                   | subtração                                                    |
| multiply                                                   | multiplicação                                                |
| divide                                                     | divisão                                                      |
| floor_divide                                               | divisao inteira                                              |
| power                                                      | potenciação                                                  |
| maximum, fmax                                              | maior entre os elementos                                     |
| minimum, fmin                                              | menor entre os elementos                                     |
| mod                                                        | módulo, o resto da divisão                                  |
| copysign                                                   | copia o sinal dos elementos do segundo array para o primeiro |
| greater, less, equal, greater_equal, less_equal, not_equal | operadores de comparação entre elementos                     |
| logical_and, logical_or, logical_xor                       | operadores lógicos entre elementos                           |

##Exemplos:   

In [ ]:
import numpy as np
l1=[0,2,4,6,8]
l2=[9,-7,5,-3,1]
a1=np.asarray(l1)
a2=np.asarray(l2)

print(a1)
print(a2)

print(np.power(a2,4))
print(np.divide(a1,a2))
print(np.divide(a2,a1))
print(np.logical_and(a1,a2))

[0 2 4 6 8]
[ 9 -7  5 -3  1]
[6561 2401  625   81    1]
[ 0.         -0.28571429  0.8        -2.          8.        ]
[   inf -3.5    1.25  -0.5    0.125]
[False  True  True  True  True]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in true_divide
  if sys.path[0] == '':


# *numpy.where()* - condicionais em arrays

É possível aplicar expressões condicionais com a função vetorizada *numpy.where()*, que tem a forma:     
`numpy.where(condição, array1, array2)`

De modo que, para a condição:    
* verdadeira: retorna o valor de array1
* falsa: retorna o valor de array2

##Exemplo:



In [ ]:
import numpy as np
l1=[0,2,4,6,8]
l2=[9,-7,5,-3,1]
a1=np.asarray(l1)
a2=np.asarray(l2)
print("a1= ",a1)
print("\na2= ",a2)

print("\nFazendo: r1=np.where(a1>a2,a1,a2)")
r1=np.where(a1>a2,a1,a2)
print(r1)


print("\nFazendo: r2=np.where(a1>a2,0,a2)")
r2=np.where(a1>a2,0,a2)
print(r2)

print("\nFazendo: r3=np.where(a1>a2,1,-1)")
r3=np.where(a1>a2,1,-1)
print(r3)


a1=  [0 2 4 6 8]

a2=  [ 9 -7  5 -3  1]

Fazendo: r1=np.where(a1>a2,a1,a2)
[9 2 5 6 8]

Fazendo: r2=np.where(a1>a2,0,a2)
[9 0 5 0 0]

Fazendo: r3=np.where(a1>a2,1,-1)
[-1  1 -1  1  1]
